import './style.css';
import { imageDataFromBlob, imageDataFromCanvas, canvasFromImageData } from './image-utils';
import { WebGPUInpaintingProvider } from './webgpu-provider';
import { TimingInfo } from './types';
import { detectLikelyWatermark } from './mask-utils';

const app = document.querySelector<HTMLDivElement>('#app')!;
app.innerHTML = `<header><div><span class="eyebrow">ANYPNG / LOCAL AI</span><h1>Inpaint images privately</h1><p>Mask an unwanted overlay and reconstruct it locally in your browser.</p></div><div id="gpu-badge" class="badge">Checking WebGPU…</div></header>
<main><section class="workspace"><div id="dropzone" class="dropzone"><input id="file" type="file" accept="image/png,image/jpeg,image/webp" hidden><button id="upload" class="primary">Upload image</button><span>or drop a PNG, JPG, or WebP here</span></div><div id="canvas-wrap" class="canvas-wrap hidden"><div id="stage"><canvas id="image-canvas"></canvas><canvas id="mask-canvas"></canvas></div></div><div class="toolbar"><label>Brush <input id="brush" type="range" min="4" max="240" value="48"><output id="brush-value">48 px</output></label><label>Mask opacity <input id="opacity" type="range" min="10" max="100" value="55"></label><div class="buttons"><button data-mode="paint" class="tool active">Paint</button><button data-mode="erase" class="tool">Erase</button><button id="undo" class="tool">Undo</button><button id="redo" class="tool">Redo</button><button id="clear" class="tool">Clear</button></div><div class="buttons"><button id="fit" class="tool">Fit</button><button id="reset" class="tool">Reset view</button><button id="before" class="tool">Hold for original</button></div></div></section>
<aside><section class="card"><h2>Inference</h2><div class="segmented"><label><input type="radio" name="size" value="512" checked>512</label><label><input type="radio" name="size" value="768">768</label><label><input type="radio" name="size" value="1024">1024</label><label><input type="radio" name="size" value="auto">Auto</label></div><button id="run" class="primary full" disabled>Remove selected area</button><div id="status" class="status">Upload an image to begin.</div></section><section class="card"><h2>Export</h2><select id="format"><option value="png">PNG</option><option value="jpeg">JPEG</option><option value="webp">WebP</option></select><label class="quality">Quality <input id="quality" type="range" min="10" max="100" value="92"><output id="quality-value">92%</output></label><button id="download" class="secondary full" disabled>Download result</button></section><section class="card diagnostics"><h2>Diagnostics</h2><dl><dt>WebGPU</dt><dd id="gpu-detail">—</dd><dt>Model</dt><dd id="model-time">—</dd><dt>Preprocess</dt><dd id="prep-time">—</dd><dt>Inference</dt><dd id="infer-time">—</dd><dt>Composite</dt><dd id="comp-time">—</dd><dt>Total</dt><dd id="total-time">—</dd></dl><div id="debug" class="debug hidden"></div></section></aside></main>`;

const imageCanvas = document.querySelector<HTMLCanvasElement>('#image-canvas')!, maskCanvas = document.querySelector<HTMLCanvasElement>('#mask-canvas')!, wrap = document.querySelector<HTMLDivElement>('#canvas-wrap')!, stage = document.querySelector<HTMLDivElement>('#stage')!;
const imageCtx = imageCanvas.getContext('2d')!, maskCtx = maskCanvas.getContext('2d')!; const provider = new WebGPUInpaintingProvider();
let source: ImageData | null = null, result: ImageData | null = null, drawing = false, mode = 'paint', opacity = .55, brush = 48, zoom = 1, history: ImageData[] = [], historyIndex = -1;
const $ = <T extends HTMLElement>(id: string) => document.querySelector<T>(`#${id}`)!;
const benchmarkButton = document.createElement('button'); benchmarkButton.id = 'benchmark'; benchmarkButton.className = 'secondary full'; benchmarkButton.disabled = true; benchmarkButton.textContent = 'Benchmark 512 / 768 / 1024'; $('run').after(benchmarkButton);
const autoMaskButton = document.createElement('button'); autoMaskButton.id = 'auto-mask'; autoMaskButton.className = 'secondary full'; autoMaskButton.disabled = false; autoMaskButton.textContent = 'Auto-detect watermark (experimental)'; benchmarkButton.after(autoMaskButton);
document.querySelectorAll<HTMLInputElement>('input[name=size]').forEach(input => { if (input.value !== '512') { input.disabled = true; input.parentElement!.title = 'This bundled LaMa model supports 512×512 only'; } }); benchmarkButton.textContent = 'Benchmark 512 (LaMa model)';

function setStatus(text: string) { $('status').textContent = text; }
function renderMask() { maskCtx.clearRect(0, 0, maskCanvas.width, maskCanvas.height); if (history[historyIndex]) maskCtx.putImageData(history[historyIndex], 0, 0); maskCtx.globalAlpha = opacity; maskCtx.globalCompositeOperation = 'source-over'; maskCtx.fillStyle = '#ff4d78'; const data = maskCtx.getImageData(0, 0, maskCanvas.width, maskCanvas.height); for (let i = 0; i < data.data.length; i += 4) { if (data.data[i + 3]) { data.data[i] = 255; data.data[i + 1] = 77; data.data[i + 2] = 120; data.data[i + 3] = Math.round(255 * opacity); } } maskCtx.putImageData(data, 0, 0); maskCtx.globalAlpha = 1; }
function render() { if (!source) return; imageCtx.putImageData(result && $('before').dataset.down !== '1' ? result : source, 0, 0); renderMask(); }
function pushHistory() { const current = maskCtx.getImageData(0, 0, maskCanvas.width, maskCanvas.height); history = history.slice(0, historyIndex + 1); history.push(current); historyIndex++; renderMask(); }
function point(event: PointerEvent) { const r = maskCanvas.getBoundingClientRect(); return { x: Math.max(0, Math.min(maskCanvas.width - 1, (event.clientX - r.left) * maskCanvas.width / r.width)), y: Math.max(0, Math.min(maskCanvas.height - 1, (event.clientY - r.top) * maskCanvas.height / r.height)) }; }
function stroke(event: PointerEvent) { const p = point(event); maskCtx.save(); maskCtx.globalCompositeOperation = mode === 'erase' ? 'destination-out' : 'source-over'; maskCtx.fillStyle = 'rgba(255,77,120,1)'; maskCtx.beginPath(); maskCtx.arc(p.x, p.y, brush / 2, 0, Math.PI * 2); maskCtx.fill(); maskCtx.restore(); renderMask(); }
function loadBlob(blob: Blob) { imageDataFromBlob(blob).then(data => { source = data; result = null; [imageCanvas.width, maskCanvas.width] = [data.width, data.width]; [imageCanvas.height, maskCanvas.height] = [data.height, data.height]; history = [new ImageData(data.width, data.height)]; historyIndex = 0; wrap.classList.remove('hidden'); $('dropzone').classList.add('hidden'); $('run').removeAttribute('disabled'); benchmarkButton.disabled = false; $('download').setAttribute('disabled', ''); fit(); render(); setStatus(`${data.width} × ${data.height} ready. Paint the area to remove.`); }).catch(() => setStatus('Could not read that image. Try PNG, JPG, or WebP.')); }
autoMaskButton.onclick = () => { if (!source) return; const detected = detectLikelyWatermark(source); if (!detected.data.some((value, index) => index % 4 === 3 && value > 0)) { setStatus('No likely watermark pixels detected. Paint the mask manually.'); return; } history = [detected]; historyIndex = 0; renderMask(); setStatus('Automatic mask created. Review it and erase any incorrect areas.'); };
function fit() { if (!source) return; const maxW = wrap.clientWidth - 24, maxH = Math.max(360, window.innerHeight * .65); zoom = Math.min(1, maxW / source.width, maxH / source.height); stage.style.transform = `scale(${zoom})`; stage.style.transformOrigin = 'top left'; wrap.style.height = `${source.height * zoom + 24}px`; }

$('upload').onclick = () => $('file').click(); $('file').onchange = () => { const file = ($('file') as HTMLInputElement).files?.[0]; if (file) loadBlob(file); }; ['dragover', 'drop'].forEach(type => $('dropzone').addEventListener(type, e => { e.preventDefault(); if (type === 'drop') { const file = (e as DragEvent).dataTransfer?.files[0]; if (file) loadBlob(file); } }));
maskCanvas.addEventListener('pointerdown', e => { drawing = true; maskCanvas.setPointerCapture(e.pointerId); stroke(e); }); maskCanvas.addEventListener('pointermove', e => { if (drawing) stroke(e); }); maskCanvas.addEventListener('pointerup', () => { if (drawing) { drawing = false; pushHistory(); } });
document.querySelectorAll<HTMLButtonElement>('.tool[data-mode]').forEach(btn => btn.onclick = () => { mode = btn.dataset.mode!; document.querySelectorAll('.tool[data-mode]').forEach(b => b.classList.toggle('active', b === btn)); }); $('brush').oninput = e => { brush = Number((e.target as HTMLInputElement).value); $('brush-value').textContent = `${brush} px`; }; $('opacity').oninput = e => { opacity = Number((e.target as HTMLInputElement).value) / 100; renderMask(); }; $('undo').onclick = () => { if (historyIndex > 0) { historyIndex--; renderMask(); } }; $('redo').onclick = () => { if (historyIndex < history.length - 1) { historyIndex++; renderMask(); } }; $('clear').onclick = () => { if (source) { maskCtx.clearRect(0, 0, source.width, source.height); pushHistory(); } }; $('fit').onclick = fit; $('reset').onclick = fit; $('before').onpointerdown = () => { $('before').dataset.down = '1'; render(); }; $('before').onpointerup = () => { delete $('before').dataset.down; render(); };
$('quality').oninput = e => $('quality-value').textContent = `${(e.target as HTMLInputElement).value}%`;

async function run() { if (!source) return; const start = performance.now(); try { setStatus('Preparing image…'); const raw = document.querySelector<HTMLInputElement>('input[name=size]:checked')!.value; const selected = raw === 'auto' ? 'auto' : Number(raw) as 512 | 768 | 1024; result = await provider.inpaint(source, history[historyIndex], { inferenceSize: selected, maskDilation: 8, cropPadding: 64, blendFeather: 8, onStatus: setStatus }); imageCtx.putImageData(result, 0, 0); $('download').removeAttribute('disabled'); const t = provider.lastTiming as TimingInfo; $('prep-time').textContent = `${Math.round(t.preprocess ?? 0)} ms`; $('infer-time').textContent = `${Math.round(t.inference ?? 0)} ms`; $('comp-time').textContent = `${Math.round(t.composite ?? 0)} ms`; $('total-time').textContent = `${Math.round(performance.now() - start)} ms`; $('status').textContent = 'Done. Hold “original” to compare.'; } catch (error) { console.error('[AnyPNG] inpainting error', error); setStatus(error instanceof Error ? error.message : 'Inpainting failed.'); } }
$('run').onclick = run; $('download').onclick = () => { if (!result) return; const format = ($('format') as HTMLSelectElement).value; const quality = Number(($('quality') as HTMLInputElement).value) / 100; const c = canvasFromImageData(result); c.toBlob(blob => { if (!blob) return; const a = document.createElement('a'); a.href = URL.createObjectURL(blob); a.download = `AnyPNG_Inpainted_${Date.now()}.${format}`; a.click(); setTimeout(() => URL.revokeObjectURL(a.href), 1000); }, `image/${format}`, format === 'png' ? undefined : quality); };
benchmarkButton.onclick = async () => { if (!source) return; const mask = history[historyIndex]; benchmarkButton.disabled = true; try { setStatus('Benchmarking 512…'); await provider.inpaint(source, mask, { inferenceSize: 512, maskDilation: 8, cropPadding: 64, blendFeather: 8 }); console.log('[AnyPNG] benchmark 512', provider.lastTiming); setStatus('Benchmark complete. See the developer console for timings.'); } catch (error) { console.error('[AnyPNG] benchmark failed', error); setStatus(error instanceof Error ? error.message : 'Benchmark failed.'); } finally { benchmarkButton.disabled = false; } };

(async () => { const badge = $('gpu-badge'); if (!navigator.gpu) { badge.textContent = 'WebGPU unavailable'; badge.classList.add('error'); $('gpu-detail').textContent = 'No'; return; } badge.textContent = 'WebGPU ready'; $('gpu-detail').textContent = 'Yes'; const debug = new URLSearchParams(location.search).get('debug') === 'true'; if (debug) $('debug').classList.remove('hidden'); try { const t = performance.now(); await provider.load(); $('model-time').textContent = `${Math.round(performance.now() - t)} ms`; setStatus('Local model ready. Upload an image to begin.'); } catch (error) { console.error('[AnyPNG] model load', error); setStatus(error instanceof Error ? error.message : 'Model could not be loaded.'); } })(); window.addEventListener('resize', fit);

async function loadExtensionJob(): Promise<void> {
  const id = new URLSearchParams(location.search).get('job'); if (!id) return;
  const blob = await new Promise<Blob>((resolve, reject) => { const request = indexedDB.open('anypng-local-editor', 1); request.onerror = () => reject(request.error); request.onsuccess = () => { const get = request.result.transaction('jobs', 'readonly').objectStore('jobs').get(id); get.onsuccess = () => get.result?.blob ? resolve(get.result.blob) : reject(new Error('The image hand-off expired.')); get.onerror = () => reject(get.error); }; });
  loadBlob(blob);
}
loadExtensionJob().catch(error => { console.error('[AnyPNG] extension image hand-off', error); setStatus(error instanceof Error ? error.message : 'Could not load the selected image.'); });

async function requestInpaintPermit(): Promise<boolean> {
  const extension = (globalThis as typeof globalThis & { chrome?: { runtime?: { sendMessage: (message: unknown) => Promise<{ authorized?: boolean; permit?: string; detail?: string }> } } }).chrome;
  if (!extension?.runtime?.sendMessage) { setStatus('Open this editor from the AnyPNG extension to use account credits.'); return false; }
  try {
    const response = await extension.runtime.sendMessage({ action: 'AUTHORIZE_INPAINT' });
    if (!response?.authorized || !response.permit) throw new Error(response?.detail || 'No inpainting credits remaining.');
    return true;
  } catch (error) { setStatus(error instanceof Error ? error.message : 'Credit authorization failed.'); return false; }
}
const originalRunHandler = $('run').onclick;
$('run').onclick = async () => { if (await requestInpaintPermit()) await originalRunHandler?.call($('run'), new PointerEvent('click')); };
const originalBenchmarkHandler = benchmarkButton.onclick;
benchmarkButton.onclick = async () => { if (await requestInpaintPermit()) await originalBenchmarkHandler?.call(benchmarkButton, new PointerEvent('click')); };
